trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build src/BleReaderNet.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
